import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  dir: "ltr",
});

// ─── Translations ─────────────────────────────────────────────────────────────
const translations: Record<string, Record<Language, string>> = {
  // App title
  "app.title": { en: "Lab Management", ar: "إدارة المختبر" },
  "app.subtitle": { en: "Construction Materials & Engineering Laboratory", ar: "مختبر الإنشاءات والمواد الهندسية" },

  // Sidebar nav
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.reception": { en: "Sample Reception", ar: "استلام العينات" },
  "nav.distribution": { en: "Distribution", ar: "التوزيع" },
  "nav.assignments": { en: "My Assignments", ar: "مهامي" },
  "nav.managerDashboard": { en: "Quality Intelligence", ar: "ذكاء الجودة" },
  "nav.adminDashboard": { en: "Main Dashboard", ar: "لوحة التحكم الرئيسية" },
  "nav.supervisorDashboard": { en: "Supervisor View", ar: "لوحة المتابعة" },
  "nav.managerReview": { en: "Test Results", ar: "نتائج الاختبارات" },
  "nav.qcReview": { en: "Quality Control", ar: "ضبط الجودة" },
  "nav.clearance": { en: "Clearance Certificate", ar: "شهادة براءة الذمة" },
  "nav.clearanceArchive": { en: "Clearance Archive", ar: "أرشيف براءة الذمة" },
  "nav.users": { en: "User Management", ar: "إدارة المستخدمين" },
  "nav.deletionRequests": { en: "Deletion Requests", ar: "طلبات الحذف" },
  "nav.tests": { en: "Tests & Contractors", ar: "الاختبارات والمقاولون" },
  "nav.analytics": { en: "Analytics & Reports", ar: "الإحصائيات والتقارير" },
  "nav.monthlyReport": { en: "Monthly Performance Report", ar: "تقرير الأداء الشهري" },
  "nav.logout": { en: "Logout", ar: "تسجيل الخروج" },
  "nav.changePassword": { en: "Change Password", ar: "تغيير كلمة المرور" },

  // Dashboard
  "dashboard.title": { en: "Dashboard", ar: "لوحة التحكم" },
  "dashboard.totalSamples": { en: "Total Samples", ar: "إجمالي العينات" },
  "dashboard.active": { en: "Active", ar: "نشطة" },
  "dashboard.completed": { en: "Completed", ar: "مكتملة" },
  "dashboard.needsAction": { en: "Needs Action", ar: "تحتاج إجراء" },
  "dashboard.todayWork": { en: "Today's Work", ar: "عمل اليوم" },
  "dashboard.workFrom": { en: "Work from", ar: "عمل من" },
  "dashboard.workOn": { en: "Work on", ar: "عمل بتاريخ" },
  "dashboard.today": { en: "Today", ar: "اليوم" },
  "dashboard.from": { en: "From", ar: "من" },
  "dashboard.to": { en: "To", ar: "إلى" },
  "dashboard.apply": { en: "Apply", ar: "تطبيق" },
  "dashboard.received": { en: "Received", ar: "مستلمة" },
  "dashboard.distributed": { en: "Distributed", ar: "موزعة" },
  "dashboard.processed": { en: "Tested", ar: "مفحوصة" },
  "dashboard.approvedIssued": { en: "Approved / Issued", ar: "معتمدة / صادرة" },
  "dashboard.noPeriodSamples": { en: "No samples registered in this period", ar: "لا توجد عينات مسجلة في هذه الفترة" },
  "dashboard.samplesByStatus": { en: "Samples by Status", ar: "العينات حسب الحالة" },
  "dashboard.samplesByType": { en: "Samples by Type", ar: "العينات حسب النوع" },
  "dashboard.recentSamples": { en: "All Recent Samples", ar: "آخر العينات المسجلة" },
  "dashboard.viewAll": { en: "View all →", ar: "عرض الكل ←" },
  "dashboard.noSamples": { en: "No samples registered yet.", ar: "لا توجد عينات مسجلة بعد." },
  "dashboard.registerFirst": { en: "Register first sample →", ar: "سجّل أول عينة ←" },
  "dashboard.noData": { en: "No data yet", ar: "لا توجد بيانات بعد" },
  "dashboard.loading": { en: "Loading...", ar: "جاري التحميل..." },
  "dashboard.uaeTime": { en: "UAE Time", ar: "توقيت الإمارات" },

  // Table headers
  "table.sampleId": { en: "Sample ID", ar: "رقم العينة" },
  "table.contractNo": { en: "Contract No.", ar: "رقم العقد" },
  "table.contractor": { en: "Contractor", ar: "المقاول" },
  "table.type": { en: "Type", ar: "النوع" },
  "table.qty": { en: "Qty", ar: "الكمية" },
  "table.status": { en: "Status", ar: "الحالة" },
  "table.receivedAt": { en: "Received At", ar: "وقت الاستلام" },
  "table.date": { en: "Date", ar: "التاريخ" },
  "table.project": { en: "Project", ar: "المشروع" },
  "table.num": { en: "#", ar: "#" },
  "table.actions": { en: "Actions", ar: "الإجراءات" },
  "table.condition": { en: "Condition", ar: "الحالة الفيزيائية" },
  "table.technician": { en: "Technician", ar: "الفني" },
  "table.result": { en: "Result", ar: "النتيجة" },
  "table.notes": { en: "Notes", ar: "ملاحظات" },
  "table.assignedAt": { en: "Assigned At", ar: "وقت التوزيع" },
  "table.completedAt": { en: "Completed At", ar: "وقت الإنجاز" },
  "table.reviewedAt": { en: "Reviewed At", ar: "وقت المراجعة" },
  "table.reviewer": { en: "Reviewer", ar: "المراجع" },
  "table.decision": { en: "Decision", ar: "القرار" },
  "table.role": { en: "Role", ar: "الدور" },
  "table.username": { en: "Username", ar: "اسم المستخدم" },
  "table.lastLogin": { en: "Last Login", ar: "آخر دخول" },
  "table.price": { en: "Price (AED)", ar: "السعر (درهم)" },
  "table.unit": { en: "Unit", ar: "الوحدة" },
  "table.code": { en: "Code", ar: "الرمز" },

  // Status labels
  "status.received": { en: "Received", ar: "مستلمة" },
  "status.distributed": { en: "Distributed", ar: "موزعة" },
  "status.testing": { en: "Testing", ar: "قيد الاختبار" },
  "status.processing": { en: "Processing", ar: "قيد المعالجة" },
  "status.processed": { en: "Tested", ar: "مفحوصة" },
  "status.manager_review": { en: "Supervisor Review", ar: "مراجعة المشرف" },
  "status.qc_review": { en: "QC Review", ar: "ضبط الجودة" },
  "status.qc_passed": { en: "QC Passed", ar: "اجتازت الجودة" },
  "status.qc_failed": { en: "QC Failed", ar: "رُفضت" },
  "status.clearance_issued": { en: "Clearance Issued", ar: "صدرت الشهادة" },
  "status.rejected": { en: "Rejected", ar: "مرفوضة" },
  "status.revision_requested": { en: "Revision Requested", ar: "طُلب تعديل" },
  "status.approved": { en: "Approved", ar: "معتمدة" },

  // Sample types
  "type.concrete": { en: "Concrete", ar: "خرسانة" },
  "type.soil": { en: "Soil", ar: "تربة" },
  "type.steel": { en: "Steel", ar: "حديد" },
  "type.asphalt": { en: "Asphalt", ar: "أسفلت" },
  "type.water": { en: "Water", ar: "مياه" },
  "type.other": { en: "Other", ar: "أخرى" },

  // Common
  "common.search": { en: "Search", ar: "بحث" },
  "common.save": { en: "Save", ar: "حفظ" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.delete": { en: "Delete", ar: "حذف" },
  "common.edit": { en: "Edit", ar: "تعديل" },
  "common.add": { en: "Add", ar: "إضافة" },
  "common.close": { en: "Close", ar: "إغلاق" },
  "common.confirm": { en: "Confirm", ar: "تأكيد" },
  "common.yes": { en: "Yes", ar: "نعم" },
  "common.no": { en: "No", ar: "لا" },
  "common.name": { en: "Name", ar: "الاسم" },
  "common.notes": { en: "Notes", ar: "ملاحظات" },
  "common.actions": { en: "Actions", ar: "الإجراءات" },
  "common.active": { en: "Active", ar: "نشط" },
  "common.inactive": { en: "Inactive", ar: "غير نشط" },
  "common.none": { en: "—", ar: "—" },
  "common.loading": { en: "Loading...", ar: "جاري التحميل..." },
  "common.noData": { en: "No data found", ar: "لا توجد بيانات" },
  "common.print": { en: "Print", ar: "طباعة" },
  "common.view": { en: "View", ar: "عرض" },
  "common.submit": { en: "Submit", ar: "إرسال" },
  "common.approve": { en: "Approve", ar: "اعتماد" },
  "common.reject": { en: "Reject", ar: "رفض" },
  "common.back": { en: "Back", ar: "رجوع" },
  "common.filter": { en: "Filter", ar: "تصفية" },
  "common.all": { en: "All", ar: "الكل" },
  "common.yes_delete": { en: "Yes, Delete", ar: "نعم، احذف" },
  "common.required": { en: "Required", ar: "مطلوب" },

  // Reception page
  "reception.title": { en: "Sample Reception", ar: "استلام العينات" },
  "reception.subtitle": { en: "Register and track incoming samples", ar: "تسجيل ومتابعة العينات الواردة" },
  "reception.registerSample": { en: "Register Sample", ar: "تسجيل عينة" },
  "reception.allSamples": { en: "All Samples", ar: "جميع العينات" },
  "reception.searchPlaceholder": { en: "Search by Sample ID, contract, or contractor...", ar: "ابحث برقم العينة أو العقد أو المقاول..." },
  "reception.completed": { en: "Completed", ar: "مكتملة" },
  "reception.inProgress": { en: "In Progress", ar: "جارية" },
  "reception.pending": { en: "Pending", ar: "معلقة" },
  "reception.totalSamples": { en: "Total Samples", ar: "إجمالي العينات" },
  "reception.newSample": { en: "New Sample Registration", ar: "تسجيل عينة جديدة" },
  "reception.editSample": { en: "Edit Sample", ar: "تعديل العينة" },
  "reception.sampleInfo": { en: "Sample Information", ar: "معلومات العينة" },
  "reception.contractInfo": { en: "Contract & Contractor", ar: "العقد والمقاول" },
  "reception.selectContract": { en: "Select Contract (optional)", ar: "اختر العقد (اختياري)" },
  "reception.contractName": { en: "Contract Name", ar: "اسم العقد" },
  "reception.contractorName": { en: "Contractor", ar: "المقاول" },
  "reception.autoFilled": { en: "Auto-filled from contract", ar: "يُملأ تلقائياً من العقد" },
  "reception.sampleType": { en: "Sample Type", ar: "نوع العينة" },
  "reception.quantity": { en: "Quantity", ar: "الكمية" },
  "reception.condition": { en: "Sample Condition", ar: "حالة العينة" },
  "reception.good": { en: "Good", ar: "جيدة" },
  "reception.damaged": { en: "Damaged", ar: "تالفة" },
  "reception.acceptable": { en: "Acceptable", ar: "مقبولة" },
  "reception.collectionDate": { en: "Collection Date", ar: "تاريخ الجمع" },
  "reception.location": { en: "Location / Site", ar: "الموقع" },
  "reception.referenceNo": { en: "Inspection Reference No.", ar: "رقم مرجع التفتيش" },
  "reception.contractorForm": { en: "Contractor form (scan)", ar: "نموذج المقاول (مسح ضوئي)" },
  "reception.priority": { en: "Priority", ar: "الأولوية" },
  "reception.normal": { en: "Normal", ar: "عادية" },
  "reception.urgent": { en: "Urgent", ar: "عاجلة" },
  "reception.critical": { en: "Critical", ar: "حرجة" },
  "reception.notes": { en: "Notes", ar: "ملاحظات" },
  "reception.registerBtn": { en: "Register Sample", ar: "تسجيل العينة" },
  "reception.deleteSample": { en: "Delete Sample", ar: "حذف العينة" },
  "reception.deleteConfirm": { en: "Are you sure you want to delete this sample?", ar: "هل أنت متأكد من حذف هذه العينة؟" },
  "reception.noSamples": { en: "No samples registered yet", ar: "لا توجد عينات مسجلة بعد" },
  "reception.noSamplesDesc": { en: "Click \"Register Sample\" to add the first sample", ar: "اضغط \"تسجيل عينة\" لإضافة أول عينة" },

  // Distribution page
  "distribution.title": { en: "Sample Distribution", ar: "توزيع العينات" },
  "distribution.subtitle": { en: "Assign samples to technicians for testing", ar: "تعيين العينات للفنيين لإجراء الاختبارات" },
  "distribution.pendingDistribution": { en: "Pending Distribution", ar: "بانتظار التوزيع" },
  "distribution.distributed": { en: "Distributed", ar: "موزعة" },
  "distribution.allSamples": { en: "All Samples", ar: "جميع العينات" },
  "distribution.assignTechnician": { en: "Assign Technician", ar: "تعيين فني" },
  "distribution.selectTechnician": { en: "Select Technician", ar: "اختر الفني" },
  "distribution.assignBtn": { en: "Assign", ar: "تعيين" },
  "distribution.reassign": { en: "Reassign", ar: "إعادة تعيين" },
  "distribution.noSamples": { en: "No samples to distribute", ar: "لا توجد عينات للتوزيع" },
  "distribution.assignedTo": { en: "Assigned to", ar: "معين لـ" },
  "distribution.unassigned": { en: "Unassigned", ar: "غير معين" },
  "distribution.bulkAssign": { en: "Bulk Assign", ar: "تعيين جماعي" },
  "distribution.selected": { en: "selected", ar: "محدد" },

  // Technician page
  "technician.title": { en: "My Assignments", ar: "مهامي" },
  "technician.subtitle": { en: "Manage your assigned samples and submit results", ar: "إدارة العينات المعينة لك وإرسال النتائج" },
  "technician.myTasks": { en: "My Tasks", ar: "مهامي" },
  "technician.pending": { en: "Pending", ar: "معلقة" },
  "technician.inProgress": { en: "In Progress", ar: "جارية" },
  "technician.completed": { en: "Completed", ar: "مكتملة" },
  "technician.submitResult": { en: "Submit Result", ar: "إرسال النتيجة" },
  "technician.startTesting": { en: "Start Testing", ar: "بدء الاختبار" },
  "technician.testType": { en: "Test Type", ar: "نوع الاختبار" },
  "technician.result": { en: "Result", ar: "النتيجة" },
  "technician.resultValue": { en: "Result Value", ar: "قيمة النتيجة" },
  "technician.unit": { en: "Unit", ar: "الوحدة" },
  "technician.passFail": { en: "Pass / Fail", ar: "ناجح / راسب" },
  "technician.pass": { en: "Pass", ar: "ناجح" },
  "technician.fail": { en: "Fail", ar: "راسب" },
  "technician.notes": { en: "Notes", ar: "ملاحظات" },
  "technician.noAssignments": { en: "No assignments yet", ar: "لا توجد مهام بعد" },
  "technician.noAssignmentsDesc": { en: "Samples will appear here once assigned to you", ar: "ستظهر العينات هنا بمجرد تعيينها لك" },
  "technician.submitSuccess": { en: "Result submitted successfully", ar: "تم إرسال النتيجة بنجاح" },
  "technician.addTest": { en: "Add Test", ar: "إضافة اختبار" },
  "technician.tests": { en: "Tests", ar: "الاختبارات" },

  // Supervisor Review page
  "managerReview.title": { en: "Test Results Review", ar: "مراجعة نتائج الاختبارات" },
  "managerReview.subtitle": { en: "Review and approve test results", ar: "مراجعة واعتماد نتائج الاختبارات" },
  "managerReview.pendingReview": { en: "Pending Review", ar: "بانتظار المراجعة" },
  "managerReview.reviewed": { en: "Reviewed", ar: "تمت المراجعة" },
  "managerReview.approve": { en: "Approve & Send to QC", ar: "اعتماد وإرسال للجودة" },
  "managerReview.reject": { en: "Reject", ar: "رفض" },
  "managerReview.requestRevision": { en: "Request Revision", ar: "طلب تعديل" },
  "managerReview.reviewNotes": { en: "Review Notes", ar: "ملاحظات المراجعة" },
  "managerReview.noSamples": { en: "No samples pending review", ar: "لا توجد عينات بانتظار المراجعة" },
  "managerReview.decision": { en: "Decision", ar: "القرار" },
  "managerReview.approved": { en: "Approved", ar: "معتمد" },
  "managerReview.rejected": { en: "Rejected", ar: "مرفوض" },
  "managerReview.revision": { en: "Revision Requested", ar: "طُلب تعديل" },

  // QC Review page
  "qcReview.title": { en: "Quality Control", ar: "ضبط الجودة" },
  "qcReview.subtitle": { en: "Quality control and final approval", ar: "ضبط الجودة والاعتماد النهائي" },
  "qcReview.pendingReview": { en: "Pending Quality Control", ar: "بانتظار ضبط الجودة" },
  "qcReview.reviewed": { en: "Reviewed", ar: "تمت المراجعة" },
  "qcReview.pass": { en: "QC Pass", ar: "اجتازت الجودة" },
  "qcReview.fail": { en: "QC Fail", ar: "رُفضت" },
  "qcReview.reviewNotes": { en: "QC Notes", ar: "ملاحظات الجودة" },
  "qcReview.noSamples": { en: "No samples pending quality control", ar: "لا توجد عينات بانتظار ضبط الجودة" },
  "qcReview.sendToClearance": { en: "Send to Clearance", ar: "إرسال للتخليص" },

  // Clearance page
  "clearance.title": { en: "Clearance Certificates", ar: "شهادة براءة الذمة" },
  "clearance.subtitle": { en: "Issue and manage clearance certificates", ar: "إصدار وإدارة شهادة براءة الذمة" },
  "clearance.issueCertificate": { en: "Issue Certificate", ar: "إصدار براءة ذمة" },
  "clearance.issued": { en: "Issued", ar: "صادرة" },
  "clearance.pending": { en: "Pending Issuance", ar: "بانتظار الإصدار" },
  "clearance.certificateNo": { en: "Certificate No.", ar: "رقم الشهادة" },
  "clearance.issuedDate": { en: "Issue Date", ar: "تاريخ الإصدار" },
  "clearance.noSamples": { en: "No samples ready for clearance", ar: "لا توجد عينات جاهزة لشهادة براءة الذمة" },
  "clearance.printCertificate": { en: "Print Certificate", ar: "طباعة شهادة براءة الذمة" },
  "clearance.viewCertificate": { en: "View Certificate", ar: "عرض شهادة براءة الذمة" },

  // Sample Detail page
  "sampleDetail.title": { en: "Sample Details", ar: "تفاصيل العينة" },
  "sampleDetail.workflow": { en: "Workflow Progress", ar: "مسار العينة" },
  "sampleDetail.info": { en: "Sample Information", ar: "معلومات العينة" },
  "sampleDetail.testResults": { en: "Test Results", ar: "نتائج الاختبارات" },
  "sampleDetail.history": { en: "History", ar: "السجل" },
  "sampleDetail.noResults": { en: "No test results yet", ar: "لا توجد نتائج اختبارات بعد" },
  "sampleDetail.registeredBy": { en: "Registered By", ar: "سجّله" },
  "sampleDetail.registeredAt": { en: "Registered At", ar: "وقت التسجيل" },
  "sampleDetail.collectionDate": { en: "Collection Date", ar: "تاريخ الجمع" },
  "sampleDetail.location": { en: "Location", ar: "الموقع" },
  "sampleDetail.priority": { en: "Priority", ar: "الأولوية" },

  // User Management page
  "users.title": { en: "User Management", ar: "إدارة المستخدمين" },
  "users.subtitle": { en: "Manage system users and their permissions", ar: "إدارة مستخدمي النظام وصلاحياتهم" },
  "users.addUser": { en: "Add User", ar: "إضافة مستخدم" },
  "users.editUser": { en: "Edit User", ar: "تعديل المستخدم" },
  "users.createUser": { en: "Create New User", ar: "إنشاء مستخدم جديد" },
  "users.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "users.username": { en: "Username", ar: "اسم المستخدم" },
  "users.password": { en: "Password", ar: "كلمة المرور" },
  "users.confirmPassword": { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  "users.role": { en: "Role", ar: "الدور" },
  "users.specialty": { en: "Specialty", ar: "التخصص" },
  "users.permissions": { en: "Permissions", ar: "الصلاحيات" },
  "users.accountInfo": { en: "Account Info", ar: "معلومات الحساب" },
  "users.accountStatus": { en: "Account Status", ar: "حالة الحساب" },
  "users.active": { en: "Active", ar: "نشط" },
  "users.inactive": { en: "Inactive", ar: "غير نشط" },
  "users.noUsers": { en: "No users yet", ar: "لا يوجد مستخدمون بعد" },
  "users.deleteConfirm": { en: "Are you sure you want to delete this user?", ar: "هل أنت متأكد من حذف هذا المستخدم؟" },
  "users.allUsers": { en: "All Users", ar: "جميع المستخدمين" },
  "users.lastLogin": { en: "Last Login", ar: "آخر دخول" },
  "users.never": { en: "Never", ar: "لم يدخل بعد" },

  // Tests & Contractors page
  "tests.title": { en: "Tests & Contractors", ar: "الاختبارات والمقاولون" },
  "tests.subtitle": { en: "Manage test types, contractors, and contracts", ar: "إدارة أنواع الاختبارات والمقاولين والعقود" },
  "tests.testTypes": { en: "Test Types", ar: "أنواع الاختبارات" },
  "tests.contractors": { en: "Contractors", ar: "المقاولون" },
  "tests.contracts": { en: "Contracts", ar: "العقود" },
  "tests.addTest": { en: "Add Test Type", ar: "إضافة نوع اختبار" },
  "tests.editTest": { en: "Edit Test Type", ar: "تعديل نوع الاختبار" },
  "tests.addContractor": { en: "Add Contractor", ar: "إضافة مقاول" },
  "tests.editContractor": { en: "Edit Contractor", ar: "تعديل المقاول" },
  "tests.addContract": { en: "Add Contract", ar: "إضافة عقد" },
  "tests.editContract": { en: "Edit Contract", ar: "تعديل العقد" },
  "tests.testName": { en: "Test Name (English)", ar: "اسم الاختبار (إنجليزي)" },
  "tests.testNameAr": { en: "Test Name (Arabic)", ar: "اسم الاختبار (عربي)" },
  "tests.standardRef": { en: "Standard Reference", ar: "المرجع القياسي" },
  "tests.unitPrice": { en: "Unit Price (AED)", ar: "سعر الوحدة (درهم)" },
  "tests.contractorName": { en: "Company Name (English)", ar: "اسم الشركة (إنجليزي)" },
  "tests.contractorNameAr": { en: "Company Name (Arabic)", ar: "اسم الشركة (عربي)" },
  "tests.contractorCode": { en: "Contractor Code", ar: "رمز المقاول" },
  "tests.contactPerson": { en: "Contact Person", ar: "جهة الاتصال" },
  "tests.phone": { en: "Phone", ar: "الهاتف" },
  "tests.email": { en: "Email", ar: "البريد الإلكتروني" },
  "tests.address": { en: "Address", ar: "العنوان" },
  "tests.contractNumber": { en: "Contract Number", ar: "رقم العقد" },
  "tests.contractName": { en: "Contract Name", ar: "اسم العقد" },
  "tests.noTests": { en: "No test types registered yet", ar: "لا توجد أنواع اختبارات مسجلة بعد" },
  "tests.noContractors": { en: "No contractors registered yet", ar: "لا يوجد مقاولون مسجلون بعد" },
  "tests.noContracts": { en: "No contracts registered yet", ar: "لا توجد عقود مسجلة بعد" },

  // Technician page — extended
  "technician.dueDate": { en: "Due Date", ar: "تاريخ الاستحقاق" },
  "technician.overdue": { en: "Overdue", ar: "متأخر" },
  "technician.daysLeft": { en: "days left", ar: "أيام متبقية" },
  "technician.daysOverdue": { en: "days overdue", ar: "يوم تأخير" },
  "technician.viewSample": { en: "View Sample", ar: "عرض العينة" },
  "technician.testForm": { en: "Test Form", ar: "نموذج الاختبار" },
  "technician.enterResults": { en: "Enter Results", ar: "إدخال النتائج" },
  "technician.manualEntry": { en: "Manual Entry", ar: "إدخال يدوي" },
  "technician.allTests": { en: "All Tests", ar: "جميع الاختبارات" },
  "technician.assignedDate": { en: "Assigned", ar: "تاريخ التعيين" },
  "technician.sampleCode": { en: "Sample Code", ar: "رمز العينة" },
  "technician.contractor": { en: "Contractor", ar: "المقاول" },
  "technician.priority.low": { en: "Low", ar: "منخفضة" },
  "technician.priority.normal": { en: "Normal", ar: "عادية" },
  "technician.priority.high": { en: "High", ar: "عالية" },
  "technician.priority.urgent": { en: "Urgent", ar: "عاجلة" },

  // Manager Review — extended
  "managerReview.sampleInfo": { en: "Sample Information", ar: "معلومات العينة" },
  "managerReview.testResults": { en: "Test Results", ar: "نتائج الاختبارات" },
  "managerReview.summary": { en: "Summary", ar: "الملخص" },
  "managerReview.passRate": { en: "Pass Rate", ar: "نسبة النجاح" },
  "managerReview.totalTests": { en: "Total Tests", ar: "إجمالي الاختبارات" },
  "managerReview.passed": { en: "Passed", ar: "نجحت" },
  "managerReview.failed": { en: "Failed", ar: "رسبت" },
  "managerReview.technician": { en: "Technician", ar: "الفني" },
  "managerReview.submittedAt": { en: "Submitted At", ar: "وقت الإرسال" },
  "managerReview.makeDecision": { en: "Make Decision", ar: "اتخاذ قرار" },
  "managerReview.sendToQC": { en: "Send to QC", ar: "إرسال لضبط الجودة" },

  // QC Review — extended
  "qcReview.sampleInfo": { en: "Sample Information", ar: "معلومات العينة" },
  "qcReview.testResults": { en: "Test Results", ar: "نتائج الاختبارات" },
  "qcReview.makeDecision": { en: "QC Decision", ar: "قرار ضبط الجودة" },
  "qcReview.passed": { en: "QC Passed", ar: "اجتازت ضبط الجودة" },
  "qcReview.failed": { en: "QC Failed", ar: "رفضت ضبط الجودة" },
  "qcReview.passRate": { en: "Pass Rate", ar: "نسبة النجاح" },
  "qcReview.totalTests": { en: "Total Tests", ar: "إجمالي الاختبارات" },
  "qcReview.reviewedBy": { en: "Reviewed By", ar: "راجعه" },
  "qcReview.reviewDate": { en: "Review Date", ar: "تاريخ المراجعة" },
  "qcReview.warnings": { en: "Warnings", ar: "تحذيرات" },
  "qcReview.allClear": { en: "All Clear", ar: "كل شيء سليم" },

  // Clearance — extended
  "clearance.requiredDocs": { en: "Required Documents", ar: "المستندات المطلوبة" },
  "clearance.contractorLetter": { en: "Contractor Letter", ar: "خطاب المقاول" },
  "clearance.sectorLetter": { en: "Sector Letter", ar: "خطاب القطاع" },
  "clearance.paymentOrder": { en: "Payment Order", ar: "أمر الدفع" },
  "clearance.paymentReceipt": { en: "Payment Receipt", ar: "إيصال الدفع" },
  "clearance.testReport": { en: "Test Report", ar: "تقرير الاختبار" },
  "clearance.remarks": { en: "Remarks", ar: "ملاحظات" },
  "clearance.allDocsRequired": { en: "All documents must be checked before issuing certificate", ar: "يجب التحقق من جميع المستندات قبل إصدار الشهادة" },
  "clearance.confirmIssue": { en: "Confirm Certificate Issuance", ar: "تأكيد إصدار الشهادة" },
  "clearance.sampleCode": { en: "Sample Code", ar: "رمز العينة" },
  "clearance.contractor": { en: "Contractor", ar: "المقاول" },
  "clearance.contract": { en: "Contract", ar: "العقد" },
  "clearance.testSummary": { en: "Test Summary", ar: "ملخص الاختبارات" },
  "clearance.issuedCertificates": { en: "Issued Certificates", ar: "الشهادات الصادرة" },

  // Sample Detail — extended
  "sampleDetail.distributions": { en: "Test Assignments", ar: "تعيينات الاختبارات" },
  "sampleDetail.reviews": { en: "Reviews", ar: "المراجعات" },
  "sampleDetail.technician": { en: "Technician", ar: "الفني" },
  "sampleDetail.testName": { en: "Test Name", ar: "اسم الاختبار" },
  "sampleDetail.result": { en: "Result", ar: "النتيجة" },
  "sampleDetail.status": { en: "Status", ar: "الحالة" },
  "sampleDetail.submittedAt": { en: "Submitted At", ar: "وقت الإرسال" },
  "sampleDetail.printReport": { en: "Print Report", ar: "طباعة التقرير" },
  "sampleDetail.viewReport": { en: "View Report", ar: "عرض التقرير" },
  "sampleDetail.noDistributions": { en: "No test assignments yet", ar: "لا توجد تعيينات بعد" },
  "sampleDetail.sector": { en: "Sector", ar: "القطاع" },
  "sampleDetail.sampleType": { en: "Sample Type", ar: "نوع العينة" },
  "sampleDetail.quantity": { en: "Quantity", ar: "الكمية" },
  "sampleDetail.condition": { en: "Condition", ar: "الحالة" },
  "sampleDetail.contract": { en: "Contract", ar: "العقد" },
  "sampleDetail.contractor": { en: "Contractor", ar: "المقاول" },

  // Reception — extended
  "reception.requestedTest": { en: "Requested Test", ar: "الاختبار المطلوب" },
  "reception.selectTest": { en: "Select Test Type (optional)", ar: "اختر نوع الاختبار (اختياري)" },
  "reception.sector": { en: "Sector", ar: "القطاع" },
  "reception.selectSector": { en: "Select Sector (optional)", ar: "اختر القطاع (اختياري)" },
  "reception.sampleCode": { en: "Sample Code", ar: "رمز العينة" },
  "reception.receivedAt": { en: "Received At", ar: "وقت الاستلام" },
  "reception.status": { en: "Status", ar: "الحالة" },
  "reception.actions": { en: "Actions", ar: "الإجراءات" },

  // Distribution — extended
  "distribution.subtype": { en: "Subtype", ar: "النوع الفرعي" },
  "distribution.testName": { en: "Test Name", ar: "اسم الاختبار" },
  "distribution.expectedCompletion": { en: "Expected Completion", ar: "تاريخ الإنجاز المتوقع" },
  "distribution.createOrder": { en: "Create Distribution Order", ar: "إنشاء أمر التوزيع" },
  "distribution.price": { en: "Price", ar: "السعر" },
  "distribution.standard": { en: "Standard", ar: "المعيار" },

  // Test forms — common labels
  "testForm.sampleInfo": { en: "Sample Information", ar: "معلومات العينة" },
  "testForm.measurements": { en: "Measurements", ar: "القياسات" },
  "testForm.results": { en: "Results", ar: "النتائج" },
  "testForm.save": { en: "Save Results", ar: "حفظ النتائج" },
  "testForm.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "testForm.saved": { en: "Results saved successfully", ar: "تم حفظ النتائج بنجاح" },
  "testForm.pass": { en: "PASS", ar: "مقبول" },
  "testForm.fail": { en: "FAIL", ar: "مرفوض" },
  "testForm.required": { en: "Required field", ar: "حقل مطلوب" },
  "testForm.autoCalc": { en: "Auto-calculated", ar: "يحسب تلقائياً" },
  "testForm.standard": { en: "Standard", ar: "المعيار" },
  "testForm.criteria": { en: "Acceptance Criteria", ar: "معايير القبول" },
  "testForm.chart": { en: "Chart", ar: "الرسم البياني" },
  "testForm.noData": { en: "Enter measurements to see chart", ar: "أدخل القياسات لعرض الرسم" },
  "testForm.specimen": { en: "Specimen", ar: "عينة" },
  "testForm.average": { en: "Average", ar: "المتوسط" },
  "testForm.min": { en: "Min", ar: "الحد الأدنى" },
  "testForm.max": { en: "Max", ar: "الحد الأعلى" },
  "testForm.limit": { en: "Limit", ar: "الحد" },
  "testForm.value": { en: "Value", ar: "القيمة" },
  "testForm.unit": { en: "Unit", ar: "الوحدة" },
  "testForm.notes": { en: "Notes", ar: "ملاحظات" },
  "testForm.date": { en: "Test Date", ar: "تاريخ الاختبار" },
  "testForm.operator": { en: "Operator", ar: "المشغل" },
  "testForm.witness": { en: "Witness", ar: "الشاهد" },
  "testForm.location": { en: "Location", ar: "الموقع" },
  "testForm.project": { en: "Project", ar: "المشروع" },
  "testForm.specifiedStrength": { en: "Specified Strength", ar: "المقاومة المحددة" },
  "testForm.age": { en: "Age (days)", ar: "العمر (يوم)" },
  "testForm.diameter": { en: "Diameter", ar: "القطر" },
  "testForm.height": { en: "Height", ar: "الارتفاع" },
  "testForm.length": { en: "Length", ar: "الطول" },
  "testForm.width": { en: "Width", ar: "العرض" },
  "testForm.mass": { en: "Mass", ar: "الكتلة" },
  "testForm.load": { en: "Load", ar: "الحمل" },
  "testForm.strength": { en: "Strength", ar: "المقاومة" },
  "testForm.density": { en: "Density", ar: "الكثافة" },
  "testForm.moisture": { en: "Moisture Content", ar: "نسبة الرطوبة" },
  "testForm.compaction": { en: "Compaction", ar: "الدمك" },
  "testForm.cbr": { en: "CBR Value", ar: "قيمة CBR" },
  "testForm.yieldStrength": { en: "Yield Strength", ar: "حد الخضوع" },
  "testForm.tensileStrength": { en: "Tensile Strength", ar: "مقاومة الشد" },
  "testForm.elongation": { en: "Elongation", ar: "الاستطالة" },
  "testForm.bitumenContent": { en: "Bitumen Content", ar: "محتوى البيتومين" },
  "testForm.marshall": { en: "Marshall Stability", ar: "ثبات مارشال" },
  "testForm.flow": { en: "Flow", ar: "التدفق" },
  "testForm.voids": { en: "Air Voids", ar: "الفراغات" },
  "testForm.gradation": { en: "Gradation", ar: "التدرج" },
  "testForm.passing": { en: "% Passing", ar: "نسبة المرور" },
  "testForm.retained": { en: "% Retained", ar: "نسبة المتبقي" },
  "testForm.sieveSize": { en: "Sieve Size", ar: "حجم المنخل" },
  "testForm.massRetained": { en: "Mass Retained (g)", ar: "الكتلة المتبقية (غ)" },
  "testForm.cumulativeRetained": { en: "Cumulative % Retained", ar: "نسبة المتبقي التراكمي" },
  "testForm.cumulativePassing": { en: "Cumulative % Passing", ar: "نسبة المرور التراكمي" },
  "testForm.fineness": { en: "Fineness Modulus", ar: "معامل النعومة" },
  "testForm.specificGravity": { en: "Specific Gravity", ar: "الوزن النوعي" },
  "testForm.absorption": { en: "Water Absorption", ar: "امتصاص الماء" },
  "testForm.initialSet": { en: "Initial Setting Time", ar: "زمن الشك الابتدائي" },
  "testForm.finalSet": { en: "Final Setting Time", ar: "زمن الشك النهائي" },
  "testForm.penetration": { en: "Penetration (mm)", ar: "الاختراق (مم)" },
  "testForm.time": { en: "Time (min)", ar: "الوقت (دقيقة)" },
  "testForm.addRow": { en: "Add Row", ar: "إضافة صف" },
  "testForm.removeRow": { en: "Remove Row", ar: "حذف صف" },
  "testForm.proctor": { en: "Proctor Test", ar: "اختبار بروكتور" },
  "testForm.mdd": { en: "MDD (g/cm³)", ar: "أقصى كثافة جافة" },
  "testForm.omc": { en: "OMC (%)", ar: "الرطوبة المثلى" },
  "testForm.fieldDensity": { en: "Field Density", ar: "الكثافة الحقلية" },
  "testForm.relativeCompaction": { en: "Relative Compaction (%)", ar: "الدمك النسبي (%)" },
  "testForm.liquidLimit": { en: "Liquid Limit (%)", ar: "حد السيولة (%)" },
  "testForm.plasticLimit": { en: "Plastic Limit (%)", ar: "حد اللدونة (%)" },
  "testForm.plasticityIndex": { en: "Plasticity Index", ar: "دليل اللدونة" },
  "testForm.classification": { en: "Classification", ar: "التصنيف" },
  "testForm.sprayRate": { en: "Spray Rate (L/m²)", ar: "معدل الرش (لتر/م²)" },
  "testForm.tankBefore": { en: "Tank Before (L)", ar: "الخزان قبل (لتر)" },
  "testForm.tankAfter": { en: "Tank After (L)", ar: "الخزان بعد (لتر)" },
  "testForm.sprayedArea": { en: "Sprayed Area (m²)", ar: "المساحة المرشوشة (م²)" },
  "testForm.coatType": { en: "Coat Type", ar: "نوع الطبقة" },
  "testForm.tackCoat": { en: "Tack Coat", ar: "طبقة التلصق" },
  "testForm.primeCoat": { en: "Prime Coat", ar: "طبقة الأساس" },
  "testForm.bitumenGrade": { en: "Bitumen Grade", ar: "درجة البيتومين" },
  "testForm.extractionMethod": { en: "Extraction Method", ar: "طريقة الاستخلاص" },
  "testForm.correctionFactor": { en: "Correction Factor (CF)", ar: "عامل التصحيح (CF)" },
  "testForm.temperatureFactor": { en: "Temperature Factor (TF)", ar: "عامل الحرارة (TF)" },
  "testForm.acv": { en: "ACV (%)", ar: "قيمة السحق (%)" },
  "testForm.aiv": { en: "AIV (%)", ar: "قيمة الصدم (%)" },
  "testForm.laValue": { en: "LA Value (%)", ar: "قيمة لوس أنجلوس (%)" },
  "testForm.gradingClass": { en: "Grading Class", ar: "فئة التدرج" },
  "testForm.revolutions": { en: "Revolutions", ar: "عدد الدورات" },
  "testForm.massBefore": { en: "Mass Before (g)", ar: "الكتلة قبل (غ)" },
  "testForm.massAfter": { en: "Mass After (g)", ar: "الكتلة بعد (غ)" },
  "testForm.flexuralStrength": { en: "Flexural Strength", ar: "مقاومة الانحناء" },
  "testForm.beamSize": { en: "Beam Size", ar: "أبعاد الكمرة" },
  "testForm.span": { en: "Span (mm)", ar: "البحر (مم)" },
  "testForm.breakPosition": { en: "Break Position", ar: "موضع الكسر" },
  "testForm.middleThird": { en: "Middle Third", ar: "الثلث الأوسط" },
  "testForm.outsideMiddle": { en: "Outside Middle Third", ar: "خارج الثلث الأوسط" },
  "testForm.bendResult": { en: "Bend Result", ar: "نتيجة الانحناء" },
  "testForm.rebendResult": { en: "Rebend Result", ar: "نتيجة الانحناء العكسي" },
  "testForm.satisfactory": { en: "Satisfactory", ar: "مرضي" },
  "testForm.unsatisfactory": { en: "Unsatisfactory", ar: "غير مرضي" },
  "testForm.coreDepth": { en: "Core Depth (mm)", ar: "عمق اللبة (مم)" },
  "testForm.coreDiameter": { en: "Core Diameter (mm)", ar: "قطر اللبة (مم)" },
  "testForm.marshallDensity": { en: "Marshall Density (g/cm³)", ar: "كثافة مارشال (g/cm³)" },
  "testForm.bulkDensity": { en: "Bulk Density (g/cm³)", ar: "الكثافة الكلية (g/cm³)" },
  "testForm.compactionDegree": { en: "Degree of Compaction (%)", ar: "درجة الدمك (%)" },
  "testForm.minCompaction": { en: "Min. Compaction (%)", ar: "أدنى دمك (%)" },
  "testForm.hotBinGradation": { en: "Hot Bin Gradation", ar: "تدرج Hot Bin" },
  "testForm.jmfLimits": { en: "JMF Limits", ar: "حدود JMF" },
  "testForm.withinLimits": { en: "Within Limits", ar: "ضمن الحدود" },
  "testForm.outsideLimits": { en: "Outside Limits", ar: "خارج الحدود" },
  "testForm.anchorType": { en: "Anchor Type", ar: "نوع الأنكر" },
  "testForm.embedmentDepth": { en: "Embedment Depth (mm)", ar: "عمق التثبيت (مم)" },
  "testForm.pulloutLoad": { en: "Pullout Load (kN)", ar: "حمل السحب (kN)" },
  "testForm.designLoad": { en: "Design Load (kN)", ar: "الحمل التصميمي (kN)" },
  "testForm.foamDensity": { en: "Foam Density (kg/m³)", ar: "كثافة الرغوة (kg/m³)" },
  "testForm.foamGrade": { en: "Foam Grade", ar: "درجة الرغوة" },
  "testForm.targetDensity": { en: "Target Density", ar: "الكثافة المستهدفة" },
  "testForm.mixGradation": { en: "Mix Gradation", ar: "تدرج الخلطة" },
  "testForm.waterCementRatio": { en: "W/C Ratio", ar: "نسبة الماء/أسمنت" },
  "testForm.slump": { en: "Slump (mm)", ar: "الهبوط (مم)" },
  "testForm.airContent": { en: "Air Content (%)", ar: "محتوى الهواء (%)" },
};

// Arabic day/month names
const AR_DAYS = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
const AR_MONTHS = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"];

export function formatDateForLang(date: Date, lang: Language): string {
  if (lang === "ar") {
    const day = AR_DAYS[date.getDay()];
    const d = date.getDate();
    const month = AR_MONTHS[date.getMonth()];
    const year = date.getFullYear();
    return `${day}، ${d} ${month} ${year}`;
  }
  return date.toLocaleDateString("en-AE", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem("lang") as Language) ?? "en";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  // Apply dir and lang to <html>
  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[key]?.[lang] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
